package com.github.livingwithhippos.unchained.search.builtin

import android.content.SharedPreferences
import com.github.livingwithhippos.unchained.search.builtin.providers.TorrentsCsvProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.PirateBayProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.LimeTorrentsProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.ThirteenThirtySevenXProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.KnabenProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.BitSearchProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.TorrentzProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.Torrent9Provider
import com.github.livingwithhippos.unchained.search.builtin.providers.OxTorrentProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.Bt4gProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.TorrentKittyProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.TorrentDownloadsProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.TorrentDownloadProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.TorrentDatabaseProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.BtDiggProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.BtsowProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.FileMoodProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.MegaPeerProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.UIndexProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.ZeroMagnetProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.NekoBtProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.TheRarBgProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.NoNameClubProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.RutorProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.EztvProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.YtsProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.SubsPleaseProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.InternetArchiveProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.MikanProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.TokyoToshokanProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.AudioBookBayProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.EpubLibreProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.LinuxTrackerProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.FitGirlRepacksProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.BlueRomsProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.NyaaProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.AnimeToshoProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.AniLibriaProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.AniRenaProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.BangumiMoeProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.DmhyProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.SukebeiProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.MyPornClubProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.XxxClubProvider
import com.github.livingwithhippos.unchained.search.builtin.providers.XxxTrackerProvider

/**
 * Every built-in torrent/magnet search provider, in settings display order.
 *
 * GENERATED by tools/gen_search_providers.py — edit the table there and re-run, do not hand edit.
 */
object TorrentProviderRegistry {

    val all: List<TorrentProvider> =
        listOf(
        TorrentsCsvProvider,
        PirateBayProvider,
        LimeTorrentsProvider,
        ThirteenThirtySevenXProvider,
        KnabenProvider,
        BitSearchProvider,
        TorrentzProvider,
        Torrent9Provider,
        OxTorrentProvider,
        Bt4gProvider,
        TorrentKittyProvider,
        TorrentDownloadsProvider,
        TorrentDownloadProvider,
        TorrentDatabaseProvider,
        BtDiggProvider,
        BtsowProvider,
        FileMoodProvider,
        MegaPeerProvider,
        UIndexProvider,
        ZeroMagnetProvider,
        NekoBtProvider,
        TheRarBgProvider,
        NoNameClubProvider,
        RutorProvider,
        EztvProvider,
        YtsProvider,
        SubsPleaseProvider,
        InternetArchiveProvider,
        MikanProvider,
        TokyoToshokanProvider,
        AudioBookBayProvider,
        EpubLibreProvider,
        LinuxTrackerProvider,
        FitGirlRepacksProvider,
        BlueRomsProvider,
        NyaaProvider,
        AnimeToshoProvider,
        AniLibriaProvider,
        AniRenaProvider,
        BangumiMoeProvider,
        DmhyProvider,
        SukebeiProvider,
        MyPornClubProvider,
        XxxClubProvider,
        XxxTrackerProvider,
        )

    val byId: Map<String, TorrentProvider> = all.associateBy { it.id }

    /** The providers the user enabled, honouring the global NSFW switch. */
    fun enabled(prefs: SharedPreferences): List<TorrentProvider> {
        val nsfw = prefs.getBoolean(KEY_NSFW, false)
        return all.filter { provider ->
            prefs.getBoolean(providerKey(provider.id),
                if (provider.id == "thepiratebay")
                    prefs.getBoolean("search_provider_piratebay", provider.enabledByDefault)
                else provider.enabledByDefault) &&
                (!provider.nsfw || nsfw)
        }
    }

    fun sortFor(prefs: SharedPreferences, providerId: String): TorrentSort =
        TorrentSort.fromId(prefs.getString(sortKey(providerId), null))

    fun providerKey(id: String) = "search_provider_$id"

    fun sortKey(id: String) = "search_sort_$id"

    const val KEY_NSFW = "search_provider_nsfw"
}
